ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks
        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude: '^docs/|setup.cfg|\.txt$|\.log$|\.xyz$|\.pdb$|\.mol2$'
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 25.9.0
  hooks:
    - id: black
      exclude: '^docs/|setup.cfg|\.txt$|\.log$|\.xyz$'
      args: [--line-length=80]

- repo: https://github.com/pycqa/isort
  rev: 7.0.0
  hooks:
    - id: isort
      name: isort (python)
      exclude: '^docs/|setup.cfg|\.txt$|\.log$|\.xyz$|\.pdb$|\.mol2$'
      args: [--profile=black, --line-length=80]
